on:
    issues:
      types: [opened, closed]
  
jobs: 
    issue-ops:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - env: 
            JSON: ${{ toJson(github.event)}}
          run: echo '$JSON'

        - name: Create comment on issue
          env:
             GH_TOKEN: ${{ github.token }}
          run: |
            gh issue comment ${{ github.event.issue.number }} --body "Hello from the GitHub workflow"      

        - name: Create comment on issue with github action when bug
          uses: actions/github-script@v7
          if: contains(github.event.issue.labels.*.name, 'bug')
          with:
                script: |
                    github.rest.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: '👋 Thanks for reporting a bug!'
                    })            

        - uses: devops-actions/issue-comment-tag@v0.1.0
          name: Tag a user or team in an issue comment
          with: 
            issue: ${{ github.event.issue.number }}
            team: paulvanderende
            owner: ${{ github.repository_owner }}
            repo: ${{ github.repository }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}