on:
    issues:
      types: [opened, closed]
  
jobs: 
    issue-ops:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: Create comment on issue
          env:
             GH_TOKEN: ${{ github.token }}
          run: |
            gh issue comment ${{ github.event.issue.number }} --body "Hello from the GitHub workflow"      

        - name: Create comment on issue with github action
          uses: actions/github-script@v7
          with:
                script: |
                    github.rest.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: '👋 Thanks for reporting!'
                    })            